wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721288744
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
