wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721296984
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.14
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 168
dropout:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 1
fc_layer_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.07885162718170675
optimizer:
  desc: null
  value: sgd
