wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.001
dropout:
  desc: null
  value: 0.5287048011538247
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721231020
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      - 62
      4: 3.10.14
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
